### ISSUE TITLE
Error opening

### ISSUE THREAD

**Issue by seifreed** [kevthehermit/VolUtility#14]
[25/Mar/2016 20:10:00] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seifreed/tools/malware/VolUtility/web/views.py", line 131, in main_page
    session_list = db.get_allsessions()
NameError: global name 'db' is not defined
[25/Mar/2016 20:10:00] WARNING [django.request:170] Not Found: /favicon.ico
[27/Mar/2016 11:16:33] ERROR [web.views:61] Unable to access mongo database: text search not enabled
[27/Mar/2016 11:16:33] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seifreed/tools/malware/VolUtility/web/views.py", line 131, in main_page
    session_list = db.get_allsessions()
NameError: global name 'db' is not defined

I have MongoDB installed

Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                 Versión                  Arquitectura             Descripción
+++-======================================-========================-========================-==================================================================================
ii  mongodb                                1:2.4.9-1ubuntu2         amd64                    object/document-oriented database (metapackage)

**Comment by kevthehermit** [comment]
Looks like the database class is not loaded. What version of mongo do you have? And is pymongo installed?  I will add some better logging for dB connections

**Comment by seifreed** [comment]
Hi,

I wrote in the previous issue!

||/ Nombre                                 Versión                  Arquitectura             Descripción
+++-======================================-========================-========================-==================================================================================
ii  mongodb                                1:2.4.9-1ubuntu2         amd64                    object/document-oriented database (metapackage)

I have pymongo in the machine, the last version. I’m using Cuckoo and he needs pymongo!

Regards
--
Marc Rivero López | @seifreed | www.ecrime.info <http://www.ecrime.info/>

**Comment by kevthehermit** [comment]
It is only tested with mongo version 3.x. I have not done any testing with 2.x. I am away for a week so am unable to test more till I get back.

**Comment by hiddenillusion** [comment]
I originally received this error message when I first attempted to install it myself. For me, it was a lack of seeing @kevthehermit specifically called out [installing v3.x](https://github.com/kevthehermit/VolUtility#mongo--pymongo) of MongoDB. I suspect your issue is the same.

**Comment by kevthehermit** [comment]
I will add version checks for all the bits the need speciifc sections. And handle the error nicely.

**Comment by vnStrawHat** [comment]
you received error "NameError: global name 'db' is not defined" because mongodb server not started. Mongodb server run in port 27017 by default. Checking it before you run "./manage.py runserver 0.0.0.0:8000"
p/s: sorry for my bad english skills. I hope it will helpful.

**Comment by kevthehermit** [comment]
@seifreed any updates on your issue?

**Comment by kevthehermit** [comment]
Latest changes have better error handling and logging, if your still having issues with the new code please re open
