### ISSUE TITLE
ERROR Json Output error in yarascan

### ISSUE THREAD

**Issue by trongkyKMA** [kevthehermit/VolUtility#20]
DEBUG Running Plugin: yarascan
DEBUG   : web.views           : Running Plugin: yarascan
ERROR Json Output error in yarascan - You must specify a string (-Y) or a rules file (-y)

help me, yarascan on VolUtility don't work, can you help me :( thank you so much

**Comment by kevthehermit** [comment]
How are you using yarascan?

Are you using: 
- The Yara Scan Memory button on the Tools Bar
- The String Search Bar on the Tools Bar
- Click the plugin run button?

Then i can help.

**Comment by trongkyKMA** [comment]
ok thank you :)

**Comment by trongkyKMA** [comment]
can you check memdump ?? I see it does not work

**Comment by kevthehermit** [comment]
You can not use the plugin run button. You need to use the yara scan memory button on the tool bar (yara needs user defined paramaters)

**Comment by kevthehermit** [comment]
I will set the yarascan plugin option to not appear.

**Comment by trongkyKMA** [comment]
ok, thank you :) can you check memdump ,it not work

**Comment by kevthehermit** [comment]
Working on it now. :) Would like to keep different issues separate

**Comment by trongkyKMA** [comment]
i don't understand. I scan file memory dump, choise button 'memdump' >>> loaddd >> error :(((

**Comment by kevthehermit** [comment]
This issue was opened for yarascan not memdump

Use this issue for memdump --> https://github.com/kevthehermit/VolUtility/issues/21
