### ISSUE TITLE
List supported plugins sorted

### ISSUE THREAD

**Issue by hiddenillusion** [kevthehermit/VolUtility#23]
Possibly just an o.c.d. thing but I think it'd be useful to display the list of supported plugins sorted. Makes it easier to quickly run what you're looking for if they're listed in order, vs. ctrl+F'ing in the browser.

This can easily be done either in [vol_interface.py](https://github.com/kevthehermit/VolUtility/blob/9effa5b32577c96241a36e6695e00d451124e121/web/vol_interface.py#L156) or [views.py](https://github.com/kevthehermit/VolUtility/blob/4395479e33354143e891cf54995643adf3d90b83/web/views.py#L246)

**Comment by kevthehermit** [comment]
There should be a filter at the top of the plugins list to quickly search. So no need to ctrl+f. 

Buy will look at sorting propey.

**Comment by Beercow** [comment]
Shouldn't this issue be closed? The sorting issue should be resolved.

**Comment by kevthehermit** [comment]
Should be listed in order of Last Run, then others alphabetically. Plus search filter so unless there is a better way of sorting., Closing
