### ISSUE TITLE
Files Detail button issue

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#30]
When opening the memdump, dumpfiles results, the Files Detail button is missing. (appears to be an issue with memdumps columns when there is more than one file to)
![2016-06-15-110919_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/16088245/dbb3b29e-32eb-11e6-9b43-c8d58750fb4d.png)
![2016-06-15-111543_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/16088273/fc939b5a-32eb-11e6-9ce5-18894cb9de4e.png)
The only way I am able to get the buttons to show up is if I click on the column sorter. (this is not possible with memdump because the sorter is missing when there is more than one file)
![2016-06-15-111611_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/16088393/88fc9830-32ec-11e6-9801-a2617e330946.png)

**Comment by kevthehermit** [comment]
On it :)

**Comment by kevthehermit** [comment]
Fixed the issue with the extra row ID's being inserted on dumpfiles and memdump. (You will need to delete the plugin output and rerun in order to reset the duplicate ID numbers per row.) 
I Cant replicate teh issue your having with the link not displaying properly. Will leave open and test some more tomorrow

**Comment by Beercow** [comment]
Sounds good. Let me know if there is any other information you need.

**Comment by Beercow** [comment]
Update. I do not have the issue with the Files Detail button not showing up in v0.1-alpha or v0.2. Something has changed in the master branch to cause this issue for me. Hope this helps.

**Comment by Beercow** [comment]
Tracked down when the issue started happening for me. 
Remove randome debug alert 7bff989 (the button shows up)
Bookmarks f062b5e (the button does not show up until I click the column sorter)
Have not figured out what is causing it though.

**Comment by Beercow** [comment]
No sure if the two are related, the column sort buttons stopped sorting for me since Server Side Pagination of data. eec5e85

**Comment by kevthehermit** [comment]
Still cant replicate this one. Buttons are fine for me. 

What Browser / OS are you seeing this on?
Have you tried clearing Cache / Incognoito or Private Browsing in case its some cached JS?

**Comment by kevthehermit** [comment]
OK Found it, Looking at it now

**Comment by kevthehermit** [comment]
Yeah OK this was a stupid mistake to make. Accidentally removed one word from a template which was then forcing any HTML in the table cells to be escaped. 

Should be fixed now.

**Comment by Beercow** [comment]
Awesome. Thank you. That works. Can you check into the column sorting if you get time? If you look further up, I was able to narrow it down to a commit.

**Comment by kevthehermit** [comment]
Ok Column sorting should be ok now as well. If you can test and let me know. I will then close the issue 

Many thanks :)

**Comment by Beercow** [comment]
Thank you, everything is working. Keep up the excellent work.
