### ISSUE TITLE
command document too large error

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#31]
Sorry to bother you again, I am not familiar with python web applications or I would troubleshoot these myself. Getting an error when running the mftparser plugin:

[16/Jun/2016 13:09:10] "POST /ajaxhandler/dropplugin/ HTTP/1.1" 200 2
[16/Jun/2016 13:09:11] "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 98050
DEBUG Running Plugin: mftparser
DEBUG   : web.views           : Running Plugin: mftparser
Scanning for MFT entries and building directory, this can take a while
ERROR Error: Unable to Store Output for mftparser - command document too large
ERROR   : web.views           : Error: Unable to Store Output for mftparser - command document too large
[16/Jun/2016 13:16:19] "POST /ajaxhandler/runplugin/ HTTP/1.1" 200 72
[16/Jun/2016 13:16:20] "POST /ajaxhandler/pollplugins/ HTTP/1.1" 200 97961

**Comment by kevthehermit** [comment]
No need to be sorry, If people dont tell me where the bugs are i can not fix them :) Send all that you find.

For this one mongo has a max document size of 16mb to store the json object in. Seems on occasion MFT and other large data sets will break this. 

I can compress in to the database but this will affect the full text search.
Maybe some logic that only those too large will be compressed. 

Or i can store in GridFS whcih will also affect its ability to full text search

**Comment by Beercow** [comment]
This confirms what I was reading up on. I wish I could provide more input on a possible solution, but my knowledge in databases and web apps in python is limited. The only input I can provide is that it is a known limitation. With the nature of dealing with memory and some of the structures can be quite large, this might have to be a back burner issue for now. I was reading that you can change the limit in the mongo source and then compile it, but I do not know what ramifications this would cause. Your work is much appreciated. People do not say that often enough.

**Comment by kevthehermit** [comment]
Ok, Its fixed, Still needs some more thorough testing but looks ok so far. 
If a plugin result is larger than the 16Mb limit then its stored in the GridFS store. with a pointer placed in the main plugin json entry. 

All entries under this limit are still stored as normal.

This means we can store the large outputs, table search and filter still works But the global plugin search will not be able to search this data. 

Should be backwards compatible with any existing data in the db so you shouldnt need to start a new session
Should be backwards compatible, i.e. this should still allow

**Comment by Beercow** [comment]
Still receiving the same error on this when using mftparser. I'm using the GrrCON 2015 target1.rar if that helps.

**Comment by kevthehermit** [comment]
Done now. My document check size was too high. Have lowered it and tested again including the GrrCon target1 mem image.

**Comment by Beercow** [comment]
Thanks again. Issuse is resolved.
