### ISSUE TITLE
Process Map button not working

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#33]
I tried to use the process map button but an image did not show up in the web interface. Everything looks like it completed bu nothing appears. I have not had a chance to look through the commits yet to see when it did/did not work.

**Comment by kevthehermit** [comment]
Works OK here for me. 

Do you see a a log line like

```[22/Jun/2016 22:35:56] "POST /ajaxhandler/dottree/ HTTP/1.1" 200 6929```

Also which browser are you using, I use viz.js to render the dot graph. I have only tested in Chrome / Firefox  On Windows and Ubuntu

**Comment by Beercow** [comment]
I do see the log line. The cat (funny by the way) leaves the screen but the image does not appear. I am using Firefox 27 on Ubuntu 14.04. Is there any way I can tell if the dot file is being produced? Just trying to troubleshoot on my end.

**Comment by kevthehermit** [comment]
You can check the web console in firefox and see if the post response
contsins a json object. If it does it's the viz is renderer. I expect this
is the case if your seeing a 200 response after the cat :). Will spin up my
Ubuntu box tomorrow and retest

**Comment by Beercow** [comment]
Update. Works fine in Chrome. Firefox version is 47 not 27. Issue is with Firefox.

**Comment by kevthehermit** [comment]
Found the issue, switching the dot render library to another one. This also gives me zoom etc in the map output. 

Will take me a couple of days to implement but im working on it now :)

**Comment by Beercow** [comment]
Just an idea, don't know if it's possible. If it can be saved in a svg format, this would allow for infinite zoom and make the image searchable. :)

**Comment by kevthehermit** [comment]
Thats what i have done :) Just formatting the data in each of the boxes that get displayed

**Comment by Beercow** [comment]
Hmmm. I see the posability of clickable nodes in the future. Could make for some interesting use cases. I'll have to do some reading on web apps so I can help out more down the road instead of just finding bugs :)

**Comment by kevthehermit** [comment]
Now generates an SVG instead of a PNG.

Still needs some tweaking to the style, alignment and i would like to add a png download option.

But for now it works again. Tested in Chrome 51 and in FF 47 on Ubuntu 14.04 x64

**Comment by Beercow** [comment]
Still not receiving a graph in FF 47 on Ubuntu 14.04 x64
![2016-06-24-134710_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/16347491/9c8329b4-3a12-11e6-8b8d-048487e1808c.png)

**Comment by Beercow** [comment]
Not working Chrome either now :(

**Comment by Beercow** [comment]
My bad. Cleared the cache. All is well. lol

**Comment by kevthehermit** [comment]
So whats working and whats not at the moment

**Comment by Beercow** [comment]
It's all good. I cleared the cache in both browsers. I'm an idiot. lol

**Comment by kevthehermit** [comment]
awesome cheers :)

**Comment by Beercow** [comment]
Future idea/request. Would it be possible to make process map a tab? Say for example, you click the process map tab. The process tab opens and generates the graph. If there is a way to save this data, every time you open the tab thereafter, the graph would be presented.
