### ISSUE TITLE
Bookmarks do not show up until plugin results are reloaded.

### ISSUE THREAD

**Issue by Beercow** [kevthehermit/VolUtility#34]
When you bookmark an item, it does not show up until the plugin results are reloaded. I think the problem is the bookmark command. The command updates the plugin but the plugin reults are not refreshed.

**Comment by kevthehermit** [comment]
Keep them coming :)

**Comment by Beercow** [comment]
Wish I could be more help with fixing things. Trying to read up on django when I have time :)

**Comment by kevthehermit** [comment]
This one should be fixed now. :)

**Comment by Beercow** [comment]
Works like a charm! Thanks again :)
