### ISSUE TITLE
Spaghetti-Os! Server Generated an Error 500 Please check the console. Typically volitility couldnt handle a plugin correctly

### ISSUE THREAD

**Issue by trongkyKMA** [kevthehermit/VolUtility#36]
i scan file dump server 2012,but modul scan dlllist not work,can  you help me

**Comment by kevthehermit** [comment]
Can you give me the output from the console log please. There is also a volutility.log file that is generated. You can find more error details in this section.

**Comment by kevthehermit** [comment]
Closing. If you can provide me with more information i will try to help
