### ISSUE TITLE
Change the virustotal-api to vt

### ISSUE THREAD

**Issue by seifreed** [kevthehermit/VolUtility#39]
Hi,

It's better change the actual virustotal-api to https://github.com/doomedraven/VirusTotalApi

Have more capabilities, and it's currently being updated

Regards

**Comment by kevthehermit** [comment]
Thanks, currently on my summer leave but will have a look when i get back.

**Comment by kevthehermit** [comment]
I am happy with the current API, if things change in the future i will revisit.
