### ISSUE TITLE
consider running 'imageinfo' plugin on-demand

### ISSUE THREAD

**Issue by hiddenillusion** [kevthehermit/VolUtility#4]
While the information from the plugin `imageinfo` is useful, it can add a timely overhead (especially on larger memory dumps). Currently, VolUtility is running it by default when creating a [new session] (https://github.com/kevthehermit/VolUtility/blob/3cdd591bd5ba3e169b4a0e8370792054b8d6adf3/web/views.py#L224) when it's truly not needed to create the session and begin running other plugins for analysis.

I propose just creating the session and having an option to run `imageinfo` like any other plugin via VolUtility, otherwise, users may end up in a wait hold just to get this information.

**Comment by kevthehermit** [comment]
Makes sense. Will leave it off unless AutoDetect has been selected. or it fails to parse with the selected profile selection.

**Comment by hiddenillusion** [comment]
Makes sense. It might be worth looking at `kdbgscan` for _AutoDetect_ since it'll be faster.
