### ISSUE TITLE
Volshell interface

### ISSUE THREAD

**Issue by sarif790** [kevthehermit/VolUtility#45]
Cool future feature would be an interactive ipython interface for volshell built into the UI

**Comment by kevthehermit** [comment]
If anyone knows how to run a shell in a web ui please let me know and i will work on this.

**Comment by kevthehermit** [comment]
Its not quiet interactive. But you can open a volshell, send it commands and get the response back. 

Store the shell in a session so it doesnt need to reload every time. 

![vol_shell_a](https://cloud.githubusercontent.com/assets/2545096/20462997/d422c1d4-af21-11e6-98a6-14e7b9cf3feb.png)

![vol_shell_b](https://cloud.githubusercontent.com/assets/2545096/20462998/d7595822-af21-11e6-959e-d47300c3f69e.png)

![vol_shell_c](https://cloud.githubusercontent.com/assets/2545096/20462999/d953fe02-af21-11e6-9421-d899945c9262.png)

**Comment by Beercow** [comment]
This seems interesting. Not sure if it would suit your needs. 

https://www.leaseweb.com/labs/2014/06/command-line-access-using-shell-php/

**Comment by kevthehermit** [comment]
This is implemented now so closing this. Will try to use it more and enhance if required.
