### ISSUE TITLE
Procdump "File Detail" Empty

### ISSUE THREAD

**Issue by dlimanov** [kevthehermit/VolUtility#46]
Hello,
Thank you for making this awesome front-end! I have a quick question: have you seen where procdump lists processes correctly but clicking on "File Details" under StoredFile column doesn't return anything for any file listed? This is via Docker, running Volatility against Win7SP1x64 memory dump.
Thanks!

**Comment by kevthehermit** [comment]
I will have a look when i get back home tonight.

**Comment by Lost4Now** [comment]
I had the same problem.  I noticed that the cuckoo module still loaded even though cuckoo was in the disabled list in the configuration file.  I fixed the problem by changing cuckoo to cuckoosandbox in the config file...After this the file details box popped up.

**Comment by kevthehermit** [comment]
Thanks for the update. Fixing the config file and added some better error handling. Testing the docker image now then will push an update

**Comment by kevthehermit** [comment]
This should be fixed. I have also updated the docker image to 16.04, and to include all the requirements for the existing extensions. Tested locally will test from the docker hub tomorrow (Its still building)
