### ISSUE TITLE
Ability to clear all events with a single action

### ISSUE THREAD

**Issue by hiddenillusion** [kevthehermit/VolUtility#5]
Currently when a plugin completes, or generates an error, a notification dialog box is created at the top of the analysis page. If there're multiple plugins configured to run, it can be a pain to close out of those dialog boxes individually.

I propose having the ability to clear all events with a single action (click). However, it might be worth (1) having the ability to clear all events & (2) ability to clear all events but errors... this way errors can be investigated but the bulk of the "ok" notifications can be cleared

**Comment by kevthehermit** [comment]
How about something like this

![new notifications](https://cloud.githubusercontent.com/assets/2545096/14000239/3d1b94c0-f138-11e5-8d6b-394eed408c3b.png)

**Comment by hiddenillusion** [comment]
Looks good - more organized and functional. :+1:
