### ISSUE TITLE
dumpregistry failure

### ISSUE THREAD

**Issue by marcurdy** [kevthehermit/VolUtility#52]
Failed runs testing across very disparent types of memory images.

DEBUG   : web.views           : Running Plugin: dumpregistry
ERROR Json Output error in dumpregistry - Rendering using the unified output format has not been implemented for this plugin.
ERROR   : web.views           : Json Output error in dumpregistry - Rendering using the unified output format has not been implemented for this plugin.
ERROR Json Output error in dumpregistry, Please specify a dump directory (--dump-dir)
ERROR   : web.views           : Json Output error in dumpregistry, Please specify a dump directory (--dump-dir)

**Comment by kevthehermit** [comment]
Sorry, my fault. In trying to make it more stable, i made it less. 

I have a fix on the develop branch now. 

Im currently testing all the modules and functions to make sure it working correctly before i push it to master. 

Should be tomorrow.

**Comment by marcurdy** [comment]
Thanks.  Definitely having general stability issues across many origins images.

**Comment by kevthehermit** [comment]
Made the unified output test more robust, that fixes the error you were seeing.
Let me know if your having any more issues.

**Comment by marcurdy** [comment]
Bingo!
