### ISSUE TITLE
dumpfiles NoneType is not iterable

### ISSUE THREAD

**Issue by marcurdy** [kevthehermit/VolUtility#55]
I ran a straight dumpfiles and got the triangle of module death.

DEBUG Running Plugin: dumpfiles
DEBUG   : web.views           : Running Plugin: dumpfiles
Testing:  json
ERROR argument of type 'NoneType' is not iterable
ERROR   : web.views           : argument of type 'NoneType' is not iterable
ERROR Error: Unable to run plugin dumpfiles - argument of type 'NoneType' is not iterable
ERROR   : web.views           : Error: Unable to run plugin dumpfiles - argument of type 'NoneType' is not iterable

Is there any extra debug I can give you?

**Comment by kevthehermit** [comment]
Dumpfiles itself is not set to run. It is only used to store files selected from other plugins like filescan.

It should set a default empty list when it loads an image for the first time. If it has not or it has been dropped If you use 'store file object' from the context menu on filescan output it will populate the table. 

Will add a better error msg and always create the table if it doesnt yet exist. 

I wanted to avoid just grabbing every file and storing them all at once. I can always add this as an option if its still useful, or you can jsut use the vol command line from the Tools bar dropdown.

**Comment by marcurdy** [comment]
That makes sense.  There's other ones like "strings" that I also expect never to run as-is without intelligent input added.
