### ISSUE TITLE
Cuckoo machine name vs label

### ISSUE THREAD

**Issue by marcurdy** [kevthehermit/VolUtility#56]
Debug error on procdump submission to cuckoo.
{u'error_value': u"Machine 'redactedA' does not exist. Available: "redactedB", "redactedC", u'error': True}

It queries for machines correctly, but when submitting the job, it uses the field called name instead of label.  It only works now if the name equals the label.

Cheers

**Comment by kevthehermit** [comment]
Can you confirm which version of Cuckoo you are using please. 

Brads fork or main fork and then the version number. 

I will set my cuckoo instance to match and test again.

**Comment by marcurdy** [comment]
Spender modified more-or-less current.

**Comment by kevthehermit** [comment]
Thanks will spin mine up and check

**Comment by kevthehermit** [comment]
This should be resolved in the latest batch of commits.

**Comment by marcurdy** [comment]
Excellent.

**Comment by kevthehermit** [comment]
Closing please re open if your still having issues

**Comment by marcurdy** [comment]
thanks Kevin.
