### ISSUE TITLE
Ability to tag/bookmark items in a plugins output

### ISSUE THREAD

**Issue by hiddenillusion** [kevthehermit/VolUtility#6]
Currently (via solely using the web interface) one can quickly search through the output of an executed plugin but if something interesting is found, the only options I see for any type of flagging/tagging/bookmarking is to either utilize the `Comments` feature -or- manually copy/paste the relevant data somewhere else.

The `Comments` feature is for general notes and comments but it'd be more efficient & effective from an analysis perspective to have the ability to tag/bookmark a given row within a plugins output. Otherwise, an analyst would have to check what was interesting in the comments then go back to said plugins output and find it again (_unless all the data was put in the comments section_... but, that can get sloppy & doesn't allow for other enhancements listed below)

**Tagging/bookmarking would allow for:**
_(these would lead to additional enhancements, but I believe they'd be useful usecases)_
- The analyst to later search/filter by tags/bookmarks
- The analyst to quickly see what was interesting within a specific plugins output
- The analyst to quickly see what was interesting within every plugin executed (shown collectively)

**Comment by kevthehermit** [comment]
Added a right click context menu to the plugin output tables. 

This allows you to toggle a bookmark on rows. 
![results_context_bookmark](https://cloud.githubusercontent.com/assets/2545096/14057245/08aa9356-f2f2-11e5-8906-7b97438cc646.png)
