### ISSUE TITLE
3rd Party Plugins not seen if memory image already loaded

### ISSUE THREAD

**Issue by SeattleForensics** [kevthehermit/VolUtility#69]
I loaded in a sample memory image, and later used the GUI to point to the directory where all the third party community plugins reside: "/home/username/VolUtility/communitymasterplugins". Upon restarting the server, then browser (with a cleared history), and opening the existing session for my memory sample, the community plugins did not show up.  I restarted my VM, and they still did not show up.  After deleting the old session and re-importing the memory image, the community plugins showed up.  Can anything be done to make the community plugins show up without re-importing the memory image?

**Comment by kevthehermit** [comment]
There is a green spinning refresh icon on the tools bar, on the session page. After adding your plugins to the folder clicking this button should register the new plugins to the session.

I think this is in the wiki, if not i will update the wiki to make it clearer.

**Comment by SeattleForensics** [comment]
Thanks very much Kevin! Much appreciated.
