### ISSUE TITLE
MD5 calculations not correct when recursively adding memory images

### ISSUE THREAD

**Issue by SeattleForensics** [kevthehermit/VolUtility#70]
When using the VolUtility GUI to add memory images recursively, an incorrect hash value is calculated.  Please see the linked screenshot.
![volutility-md5-issue](https://cloud.githubusercontent.com/assets/24799443/21537243/53f30a6a-cd43-11e6-8c37-04c4bfb2f3b8.png)

**Comment by kevthehermit** [comment]
That's not an MD5. That is the DB ID for the session.

**Comment by SeattleForensics** [comment]
Oh, my bad. Thanks for setting me straight! I should have looked closer; my fault. 

-Jerod
=========================
A+, CCE, EnCE, GCFA, GNFA
=========================
